# Generated by Django 3.0.4 on 2020-03-30 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_table_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanip', models.GenericIPAddressField()),
                ('organisation_name', models.CharField(max_length=128, null=True)),
                ('white_list_urls', models.URLField()),
                ('black_list_urls', models.URLField()),
                ('category_to_block', models.CharField(max_length=128)),
                ('countries_into_block', models.CharField(max_length=128)),
                ('plan_start_date', models.DateTimeField()),
                ('plan_end_date', models.DateTimeField()),
                ('current_status', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=128, null=True)),
                ('lastname', models.CharField(max_length=128, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('pincode', models.CharField(max_length=15, null=True)),
                ('modified_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
