# Generated by Django 3.0.4 on 2020-03-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_table_configuration',
            old_name='lanip',
            new_name='lan_ip',
        ),
    ]
