# Generated by Django 3.0.4 on 2020-03-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200330_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_table_configuration',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='customer_table_configuration',
        ),
    ]
